In [3]:
def convert_units():
    """
    Converts between length, weight, and volume units.
    Handles invalid input using try-except.
    """

    print("Choose conversion type:")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")

    choice = input("Enter choice (1/2/3): ")

    try:
        value = float(input("Enter value to convert: "))

        if choice == "1":
            print("1. Meters to Feet")
            print("2. Feet to Meters")
            opt = input("Choose option: ")

            if opt == "1":
                print("Result:", value * 3.28084, "ft")
            elif opt == "2":
                print("Result:", value / 3.28084, "m")

        elif choice == "2":
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            opt = input("Choose option: ")

            if opt == "1":
                print("Result:", value * 2.20462, "lb")
            elif opt == "2":
                print("Result:", value / 2.20462, "kg")

        elif choice == "3":
            print("1. Liters to Gallons")
            print("2. Gallons to Liters")
            opt = input("Choose option: ")

            if opt == "1":
                print("Result:", value * 0.264172, "gallons")
            elif opt == "2":
                print("Result:", value / 0.264172, "liters")

        else:
            print("Invalid conversion type")

    except ValueError:
        print("Invalid numeric input")

convert_units()

Choose conversion type:
1. Length
2. Weight
3. Volume
Enter choice (1/2/3): 3
Enter value to convert: 2
1. Liters to Gallons
2. Gallons to Liters
Choose option: 2
Result: 7.570825068515966 liters


In [4]:
def find_sum(lst):
    """Return sum of list"""
    return sum(lst)

def find_average(lst):
    """Return average"""
    return sum(lst) / len(lst)

def find_max(lst):
    """Return maximum"""
    return max(lst)

def find_min(lst):
    """Return minimum"""
    return min(lst)

try:
    numbers = list(map(float, input("Enter numbers separated by space: ").split()))

    print("Choose operation:")
    print("1 Sum")
    print("2 Average")
    print("3 Maximum")
    print("4 Minimum")

    op = input("Enter choice: ")

    if op == "1":
        print("Sum =", find_sum(numbers))
    elif op == "2":
        print("Average =", find_average(numbers))
    elif op == "3":
        print("Max =", find_max(numbers))
    elif op == "4":
        print("Min =", find_min(numbers))
    else:
        print("Invalid operation")

except:
    print("Invalid input")

Enter numbers separated by space: 1 3 4 6 7 8
Choose operation:
1 Sum
2 Average
3 Maximum
4 Minimum
Enter choice: 1
Sum = 29.0


In [12]:
def extract_every_other(lst):
    return lst[::2]

# Example:
print(extract_every_other([1, 2, 3, 4, 5, 6]))

[1, 3, 5]


In [13]:
def get_sublist(lst, start, end):
    return lst[start:end+1]  # +1 because slicing excludes the end index

# Example:
print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))

[3, 4, 5]


In [14]:
def reverse_list(lst):
    return lst[::-1]

# Example:
print(reverse_list([1, 2, 3, 4, 5]))

[5, 4, 3, 2, 1]


In [15]:
def remove_first_last(lst):
    return lst[1:-1]

# Example:
print(remove_first_last([1, 2, 3, 4, 5]))

[2, 3, 4]


In [16]:
def get_first_n(lst, n):
    return lst[:n]

# Example:
print(get_first_n([1, 2, 3, 4, 5], 3))

[1, 2, 3]


In [17]:
def get_last_n(lst, n):
    return lst[-n:]

# Example:
print(get_last_n([1, 2, 3, 4, 5], 2))

[4, 5]


In [18]:
def reverse_skip(lst):
    return lst[-2::-2]  # Start from second-to-last, step backwards by 2

# Example:
print(reverse_skip([1, 2, 3, 4, 5, 6]))

[5, 3, 1]


In [6]:
def flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)
    return result

# Example usage:
nested_list = [[1, 2], [3, 4], [5]]
print(flatten(nested_list))

[1, 2, 3, 4, 5]


In [7]:
def access_nested_element(lst, indices):
    element = lst
    for index in indices:
        element = element[index]  # Drill down step by step
    return element

# Example usage:
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
print(access_nested_element(lst, indices))

6


In [8]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

# Example usage:
nested_list = [[1, 2], [3, [4, 5]], 6]
print(sum_nested(nested_list))

21


In [9]:
def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item, list):
            # Recursively process sublists
            cleaned = remove_element(item, elem)
            if cleaned:  # Only add non-empty sublists
                result.append(cleaned)
        else:
            if item != elem:  # Keep only items not equal to elem
                result.append(item)
    return result

# Example usage:
lst = [[1, 2], [3, 2], [4, 5]]
elem = 2
print(remove_element(lst, elem))

[[1], [3], [4, 5]]


In [10]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)  # Recursively count inside sublists
        else:
            if item == elem:
                count += 1
    return count

# Example usage:
lst = [[1, 2], [2, 3], [2, 4]]
elem = 2
print(count_occurrences(lst, elem))  # Output: 3

3


In [11]:
def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))  # Recursively flatten sublists
        else:
            result.append(item)
    return result

# Example usage:
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(deep_flatten(nested_list))

[1, 2, 3, 4, 5, 6, 7, 8]


In [19]:
def average_nested(lst):
    def helper(sublist):
        total = 0
        count = 0
        for item in sublist:
            if isinstance(item, list):
                t, c = helper(item)  # Recursively process sublists
                total += t
                count += c
            else:
                total += item
                count += 1
        return total, count

    total, count = helper(lst)
    return total / count if count != 0 else 0

# Example usage:
nested_list = [[1, 2], [3, 4], [5, 6]]
print(average_nested(nested_list))

3.5


In [20]:
import numpy as np
import time

In [21]:
# 1 Initialize empty array 2x2
a = np.empty((2,2))
print("Empty 2x2 array:\n", a)

# 2 Initialize all ones array 4x2
b = np.ones((4,2))
print("\nOnes 4x2 array:\n", b)

# 3 Array filled with specific value
c = np.full((3,3), 7)
print("\nFull array with 7:\n", c)

# 4 Zeros array same shape as c
d = np.zeros_like(c)
print("\nZeros like c:\n", d)

# 5 Ones array same shape as c
e = np.ones_like(c)
print("\nOnes like c:\n", e)

# 6 Convert list to numpy array
new_list = [1,2,3,4]
f = np.array(new_list)
print("\nConverted list to array:\n", f)

Empty 2x2 array:
 [[7.72390023e-316 0.00000000e+000]
 [5.56569986e-307             nan]]

Ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full array with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like c:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

Ones like c:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

Converted list to array:
 [1 2 3 4]


In [22]:
# 1 Array from 10 to 49
a = np.arange(10,50)
print("Array 10-49:\n", a)

# 2 3x3 matrix from 0-8
b = np.arange(9).reshape(3,3)
print("\n3x3 Matrix:\n", b)

# 3 Identity matrix
c = np.eye(3)
print("\nIdentity matrix:\n", c)

# 4 Random array size 30 and mean
d = np.random.random(30)
print("\nRandom array:\n", d)
print("Mean:", d.mean())

# 5 Random 10x10 and find min/max
e = np.random.random((10,10))
print("\n10x10 random array:\n", e)
print("Minimum:", e.min())
print("Maximum:", e.max())

# 6 Zero array size 10 replace 5th element
f = np.zeros(10)
f[4] = 1
print("\nReplace 5th element:\n", f)

# 7 Reverse array
arr = np.array([1,2,0,0,4,0])
print("\nReversed array:\n", arr[::-1])

# 8 Border ones inside zero
g = np.ones((5,5))
g[1:-1,1:-1] = 0
print("\nBorder matrix:\n", g)

# 9 Checkerboard 8x8
h = np.zeros((8,8), dtype=int)
h[1::2, ::2] = 1
h[::2, 1::2] = 1
print("\nCheckerboard:\n", h)

Array 10-49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array:
 [0.50010462 0.78617678 0.70030154 0.25299889 0.87738918 0.15037643
 0.57882425 0.14811243 0.77405606 0.30293936 0.24112123 0.25275088
 0.77339518 0.14150284 0.44288227 0.16253625 0.82000633 0.97982859
 0.93808362 0.49522967 0.42879298 0.26672869 0.658637   0.85014319
 0.58164386 0.82919213 0.0184361  0.93714251 0.87914725 0.85265166]
Mean: 0.5540377257818665

10x10 random array:
 [[0.02689366 0.96682997 0.6382676  0.22770291 0.61323192 0.45071486
  0.98061323 0.22981629 0.2395247  0.09496038]
 [0.60964852 0.89948718 0.48426231 0.5719306  0.14718319 0.98691208
  0.1004812  0.12574687 0.37345478 0.7543045 ]
 [0.50021666 0.7829046  0.57694326 0.41629722 0.91377234 0.05618619
  0.94312376 0.833658   0.74383712 0.9968644 ]
 [0.3915968  0.679078

In [23]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

# 1 Addition
print("Addition:\n", x+y)

# 2 Subtraction
print("\nSubtraction:\n", x-y)

# 3 Multiply by integer
print("\nMultiply by 3:\n", x*3)

# 4 Square elements
print("\nSquare:\n", x**2)

# 5 Dot products
print("\nDot product v.w =", np.dot(v,w))
print("Dot product x.v =", np.dot(x,v))
print("Dot product x.y:\n", np.dot(x,y))

# 6 Concatenation
print("\nConcatenate x and y (rows):\n", np.concatenate((x,y),axis=0))
print("\nConcatenate v and w (column):\n", np.vstack((v,w)))

# 7 Concatenate x and v
try:
    print(np.concatenate((x,v)))
except Exception as e:
    print("\nError:", e)
    print("Reason: x is 2D array but v is 1D array (dimension mismatch)")

Addition:
 [[ 6  8]
 [10 13]]

Subtraction:
 [[-4 -4]
 [-4 -3]]

Multiply by 3:
 [[ 3  6]
 [ 9 15]]

Square:
 [[ 1  4]
 [ 9 25]]

Dot product v.w = 219
Dot product x.v = [29 77]
Dot product x.y:
 [[19 22]
 [50 58]]

Concatenate x and y (rows):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w (column):
 [[ 9 10]
 [11 12]]

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: x is 2D array but v is 1D array (dimension mismatch)


In [24]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1 A * A^-1 = I
A_inv = np.linalg.inv(A)
I = np.dot(A,A_inv)

print("A * A^-1 =\n", I)

# 2 AB ≠ BA
AB = np.dot(A,B)
BA = np.dot(B,A)

print("\nAB =\n", AB)
print("\nBA =\n", BA)

# 3 (AB)^T = B^T A^T
left = AB.T
right = np.dot(B.T, A.T)

print("\n(AB)^T =\n", left)
print("\nB^T A^T =\n", right)

A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB =
 [[23 13]
 [51 29]]

BA =
 [[36 44]
 [13 16]]

(AB)^T =
 [[23 51]
 [13 29]]

B^T A^T =
 [[23 51]
 [13 29]]


In [25]:
A = np.array([
    [2,-3,1],
    [1,-1,2],
    [3,1,-1]
])

B = np.array([-1,-3,9])

# Using inverse
A_inv = np.linalg.inv(A)
X = np.dot(A_inv,B)

print("Solution using inverse:")
print("x, y, z =", X)

# Using solve
solution = np.linalg.solve(A,B)

print("\nSolution using numpy solve:")
print("x, y, z =", solution)

Solution using inverse:
x, y, z = [ 2.  1. -2.]

Solution using numpy solve:
x, y, z = [ 2.  1. -2.]


In [26]:
size = 1000000

list1 = list(range(size))
list2 = list(range(size))

# Python list addition
start = time.time()
result = [list1[i] + list2[i] for i in range(size)]
print("Python addition time:", time.time()-start)

# NumPy addition
a = np.array(list1)
b = np.array(list2)

start = time.time()
c = a + b
print("NumPy addition time:", time.time()-start)

# Python multiplication
start = time.time()
result = [list1[i] * list2[i] for i in range(size)]
print("Python multiplication time:", time.time()-start)

# NumPy multiplication
start = time.time()
c = a * b
print("NumPy multiplication time:", time.time()-start)

# Python dot product
start = time.time()
dot = sum(list1[i]*list2[i] for i in range(size))
print("Python dot product time:", time.time()-start)

# NumPy dot product
start = time.time()
dot = np.dot(a,b)
print("NumPy dot product time:", time.time()-start)

Python addition time: 0.23643255233764648
NumPy addition time: 0.004845380783081055
Python multiplication time: 0.1358635425567627
NumPy multiplication time: 0.00484466552734375
Python dot product time: 0.10747051239013672
NumPy dot product time: 0.002067089080810547
